[package]
name = "enumeration"
version = "0.1.1"
description = "Add-only set of keys with numbering and two-way lookup"
repository = "https://github.com/research-ag/enumeration"
keywords = [ "set", "bijective", "map", "lookup", "key" ]
license = "Apache-2.0"

[dev-dependencies]
test = "2.0.0"

[dependencies]
base = "0.11.1"

[toolchain]
moc = "0.11.1"

